name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_5.x:
    name: Build with Qt 5.12
    runs-on: ubuntu-latest

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.11'
          modules: 'qtwebengine qtwebsockets'
      
      # Checkout repository and submodules
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        run: |
          qmake CONFIG+=release
          make
  build_6.x:
      name: Build with Qt 6.x
      runs-on: ubuntu-latest

      steps:
        - name: Install Qt
          uses: jurplel/install-qt-action@v2
          with:
            version: '6.1'
            modules: 'qtwebengine qtwebsockets'

        # Checkout repository and submodules
        - uses: actions/checkout@v2
          with:
            submodules: recursive

        - name: Build
          run: |
            qmake CONFIG+=release
            make
