name: Pre Release

on:
  workflow_run:
    workflows: ["Build"]
    branches: [master]
    types: [completed]

jobs:
  pre-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      # Checkout repository and submodules
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: "Archive all"
        run: |
          python -m pip install --upgrade pip
          pip install git-archive-all
          git-archive-all --force-submodules --prefix=globalprotect-openconnect-latest/ ./globalprotect-openconnect_latest.orig.tar.gz

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.tar.gz