name: Pre Release

on:
  workflow_run:
    workflows: ["Build"]
    branches: [master]
    types: [completed]

jobs:
  pre-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      CHANGELOG_AUTHOR_NAME: "Kevin Yue"
      CHANGELOG_AUTHOR_EMAIL: "yuezk001@gmail.com"

    steps:
      # Checkout repository and submodules
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Initial variables
        id: vars
        run: |
          TAG=$(git tag --sort=-v:refname --list "v[0-9]*" | head -n 1 | cut -c 2-)
          echo ::set-output name=VERSION::"${TAG}+SNAPSHOT$(date -u +"%Y%m%d%H%M%S")-1ppa1"

      - name: Patch changelog (snapshot)
        uses: pi-top/git-debian-changelog-bump-action@master
        with:
          release: false
          author_name: ${{ env.CHANGELOG_AUTHOR_NAME }}
          author_email: ${{ env.CHANGELOG_AUTHOR_EMAIL }}          

      - name: "Archive all"
        run: |
          python -m pip install --upgrade pip
          pip install git-archive-all
          git-archive-all \
            --force-submodules \
            --prefix=globalprotect-openconnect-${{ steps.vars.outputs.VERSION }}/ \
            ./globalprotect-openconnect_${{ steps.vars.outputs.VERSION }}.orig.tar.gz

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.tar.gz